Add pop operation
DE-labtory/koa pull request #141
Opened 2019-01-16 04:19 UTC by hea9549

resolved: #125 

details: implement pop opcode

I made a pop of vm. But I don't know if this is necessary.

- [ x ] Test case

2019-01-16 05:24 UTC, boohyunsik commented on vm/vm.go
> +	_ = stack.pop()
if pop retuns err, why don't you return err?

2019-01-17 03:24 UTC, hea9549 commented on vm/vm.go
> +	_ = stack.pop()
Do you mean stack.pop() throws an error? stack.pop() does not return an error.

2019-01-17 03:41 UTC, boohyunsik commented on vm/vm.go
> +	_ = stack.pop()
ah, I misunderstood :-D

2019-01-17 06:56 UTC, boohyunsik approved these changes
LGTM :-)

2019-01-17 06:57 UTC, hihiboss commented
Is it really fine just removing item??

@hea9549 @boohyunsik  @zeroFruit @leesd556 @junbeomlee

2019-01-17 07:12 UTC, leesd556 commented
@hihiboss 
I think it should be discussed especially with the compiler!

1. Is it ok just pop without error handling?
 -> EVM don't handle that error. why?

2. Is it ok just removing item ?
 -> EVM uses `intPool`, a temporary stack storage. why?

I'll register it to issue!

2019-01-17 07:14 UTC, AgwaB requested changes
@hihiboss 
I think it should be discussed especially with the compiler!

1. Is it ok just pop without error handling?
 -> EVM don't handle that error. why?

2. Is it ok just removing item ?
 -> EVM uses `intPool`, a temporary stack storage. why?

I'll register it to issue!

2019-01-17 08:17 UTC, hihiboss commented
@leesd556 

Ok. Thank you!

2019-01-18 06:45 UTC, hea9549 commented
> @hihiboss
> I think it should be discussed especially with the compiler!
> 
> 1. Is it ok just pop without error handling?
>    -> EVM don't handle that error. why?
> 2. Is it ok just removing item ?
>    -> EVM uses `intPool`, a temporary stack storage. why?
> 
> I'll register it to issue!

1. I submit issue about this #150 

2. I found lot's of article about intpool. In my opinion, an intpool is simply used for reuse. also written in evm's intpool.go
```
// intPool is a pool of big integers that
// can be reused for all big.Int operations.
```
It is used to reuse objects without creating new ones.

2019-01-18 07:10 UTC, AgwaB approved these changes

2019-01-18 07:11 UTC, merged