Define TokenType, Ast node, statements, literals
DE-labtory/koa pull request #23
Opened 2018-12-27 13:08 UTC by zeroFruit

resolved: #21, #22

details:

define TokenType, AST node, statement, expression, literal

2018-12-28 00:33 UTC, hihiboss commented
There is an import cycle error. `ast` imported `parse` and `parse` imported `ast`.

2018-12-28 03:39 UTC, zeroFruit commented
I solved cycle dependency problem by moving `ast.go` to `parse` package

2018-12-28 05:11 UTC, junbeomlee commented
We should think about this unused `statementNode()` function and `Node interface{}`
And i don't think the token is necessary!! This struct is not used at all in the book also.
```
type ReturnStatement struct {
 	Token <- 
 	ReturnValue Expression
 }
```
So let's talk about this.

2018-12-28 05:29 UTC, junbeomlee requested changes
We should think about this unused `statementNode()` function and `Node interface{}`
And i don't think the token is necessary!! This struct is not used at all in the book also.
```
type ReturnStatement struct {
 	Token <- this token
 	ReturnValue Expression
 }
```
So let's talk about this.

2018-12-28 05:57 UTC, zeroFruit commented
I agree with removing `Token` so fixed still keep `Node` interface and deeply consider about method names. and named Statement node for `do()` because statements basically **do something**, and Expression node for `produce()` because expression basically **produce at least one value**. Referenced from here:

https://stackoverflow.com/a/4730559/6433772

2018-12-28 07:44 UTC, hihiboss commented
If `ast.go` is moved to `parse` package, is a dependency occurs?
Because, compiler component also uses `ast.go`...
Let's talk about whether moving `ast.go` is fine or not.

2018-12-28 08:19 UTC, zeroFruit commented
@hihiboss @junbeomlee refactored!

2018-12-28 11:37 UTC, junbeomlee commented on parse/token.go
> +
Int    // 1343456
String // "hello world"
Bool   // true, false

Also we need int type tokenType

2018-12-28 12:16 UTC, zeroFruit commented
Separated Token type with AST type (operator type, datastructure type) then compiler now only needs to know about AST type not Token type!

And parser needs to map Token type with AST type when building AST. Now the dependency is:
```
lexer -> Token
parser -> Token, AST
compiler -> AST
```
We can now separate dependency between Token and AST

2018-12-28 13:09 UTC, junbeomlee approved these changes
LGTM

2018-12-29 04:57 UTC, hihiboss commented
It’s explicit!

2018-12-29 04:57 UTC, hihiboss approved these changes

2018-12-29 05:05 UTC, merged