Feature/vm/#312
DE-labtory/koa pull request #324
Opened 2019-02-16 16:56 UTC by leesd556

resolved: #312, #321

details:

- Implements integrate test case
- Implements opcode `revert`, `returning` and test case
- Implements abi/method's method and test case

I will add more integrate test case!
on progress.....

- [ ] Test case

2019-02-17 10:13 UTC, hihiboss requested changes

2019-02-17 10:13 UTC, hihiboss commented on opcode/constant.go
> +	Revert Type = 0x27
If you insert this opcode, many test cases would fail. I think you don't touch other opcode, only add `Revert` opcode.

2019-02-17 11:13 UTC, hihiboss requested changes

2019-02-17 11:13 UTC, hihiboss commented on vm/vm.go
> +	if !asm.validateJumpDst(uint64(pos)) {
We decide not to use JumpDst.

2019-02-19 07:53 UTC, hihiboss approved these changes

2019-02-19 13:33 UTC, zeroFruit approved these changes

2019-02-19 14:28 UTC, merged